/**
 * Ocean Shader Definitions for Babylon.js
 * Registers vertex and fragment shaders for ocean surface rendering
 */

import * as BABYLON from '@babylonjs/core';

export function registerOceanShaders(): void {
  // Ocean Vertex Shader - using simple wave displacement
  const oceanVertexShader = [
    'precision highp float;',
    '',
    '// Attributes',
    'attribute vec3 position;',
    'attribute vec3 normal;',
    'attribute vec2 uv;',
    '',
    '// Uniforms',
    'uniform mat4 worldViewProjection;',
    'uniform mat4 world;',
    'uniform float time;',
    'uniform float waveAmplitude;',
    'uniform float waveFrequency;',
    'uniform float windDirection;',
    '',
    '// Varyings',
    'varying vec3 vPosition;',
    'varying vec3 vNormal;',
    'varying vec2 vUV;',
    'varying float vHeight;',
    '',
    'void main() {',
    '  vec3 worldPos = position;',
    '  ',
    '  // Simple wave displacement',
    '  float wave1 = sin(worldPos.x * 0.01 + time * waveFrequency) * waveAmplitude;',
    '  float wave2 = sin(worldPos.z * 0.01 + time * waveFrequency * 0.7) * waveAmplitude * 0.7;',
    '  float wave3 = sin((worldPos.x + worldPos.z) * 0.005 + time * waveFrequency * 0.5) * waveAmplitude * 0.5;',
    '  float totalWave = wave1 + wave2 + wave3;',
    '  ',
    '  worldPos.y = worldPos.y + totalWave;',
    '  ',
    '  // Simple normal calculation',
    '  vec3 perturbedNormal = normal;',
    '  ',
    '  // Transform to clip space',
    '  gl_Position = worldViewProjection * vec4(worldPos, 1.0);',
    '  ',
    '  // Pass data to fragment shader',
    '  vPosition = (world * vec4(worldPos, 1.0)).xyz;',
    '  vNormal = (world * vec4(perturbedNormal, 0.0)).xyz;',
    '  vUV = uv;',
    '  vHeight = totalWave;',
    '}',
  ].join('\n');

  // Ocean Fragment Shader
  const oceanFragmentShader = [
    'precision highp float;',
    '',
    '// Varyings',
    'varying vec3 vPosition;',
    'varying vec3 vNormal;',
    'varying vec2 vUV;',
    'varying float vHeight;',
    '',
    '// Uniforms',
    'uniform float time;',
    '',
    'void main() {',
    '  // Lighting setup',
    '  vec3 sunDir = normalize(vec3(0.5, 1.0, 0.5));',
    '  vec3 viewDir = normalize(-vPosition);',
    '  vec3 normal = normalize(vNormal);',
    '  ',
    '  // Diffuse lighting',
    '  float diffuse = max(dot(normal, sunDir), 0.0);',
    '  ',
    '  // Specular lighting',
    '  vec3 halfDir = normalize(sunDir + viewDir);',
    '  float specular = pow(max(dot(normal, halfDir), 0.0), 64.0);',
    '  ',
    '  // Fresnel effect',
    '  float fresnel = pow(1.0 - max(dot(normal, viewDir), 0.0), 3.0);',
    '  ',
    '  // Water color gradient',
    '  vec3 waterColor = mix(',
    '    vec3(0.08, 0.45, 0.95),',
    '    vec3(0.02, 0.2, 0.55),',
    '    vHeight * 0.1',
    '  );',
    '  ',
    '  // Caustics effect - simple animated pattern',
    '  float caustics = sin(vPosition.x * 0.08 + time * 0.5) * sin(vPosition.z * 0.08 + time * 0.3);',
    '  caustics = caustics * 0.5 + 0.5;',
    '  ',
    '  // Foam on wave crests',
    '  float foam = 0.0;',
    '  if (vHeight > 0.5) {',
    '    foam = (vHeight - 0.5) * 0.6;',
    '  }',
    '  ',
    '  // Combine lighting',
    '  vec3 color = waterColor * (0.3 + diffuse * 0.7);',
    '  color = color + vec3(1.0) * specular * 0.5;',
    '  color = color + vec3(0.3, 0.5, 0.8) * fresnel * 0.3;',
    '  color = color + vec3(1.0) * caustics * 0.2;',
    '  color = color + vec3(1.0) * foam;',
    '  ',
    '  gl_FragColor = vec4(color, 1.0);',
    '}',
  ].join('\n');

  // Register shaders with Babylon.js
  BABYLON.Effect.ShadersStore['oceanVertexShader'] = oceanVertexShader;
  BABYLON.Effect.ShadersStore['oceanFragmentShader'] = oceanFragmentShader;

  console.log('✅ Ocean shaders registered with Babylon.js');
}
