import { ShaderContext } from '../ShaderContext';
import { ShaderRegistryEntry } from '../ShaderRegistry';
import { waterVertexShader, profiledOceanFragmentShader } from '../wgsl';

export const gerstnerWavesDefinition: ShaderRegistryEntry = {
  id: 'gerstnerWaves',
  displayName: 'Gerstner Waves',
  description: 'Photoreal hero-ocean profile with crisp crests and deep troughs',
  
  features: {
    supportsFoam: true,
    supportsCaustics: false,
    supportsCollisions: true,
    supportsWake: true,
  },
  
  shader: {
    vertex: waterVertexShader,
    fragment: profiledOceanFragmentShader,
  },
  
  babylon: {
    uniforms: [
      'time',
      'cameraPosition',
      'waveAmplitude',
      'waveFrequency',
      'windDirection',
      'windSpeed',
      'crestFoamEnabled',
      'crestFoamThreshold',
      'foamIntensity',
      'foamWidth',
      'foamNoiseFactor',
      'foamCellScale',
      'foamShredSlope',
      'foamFizzWeight',
      'intersectionFoamEnabled',
      'intersectionFoamIntensity',
      'intersectionFoamWidth',
      'intersectionFoamFalloff',
      'intersectionFoamNoise',
      'intersectionFoamVerticalRange',
      'boatIntersectionFactor',
      'islandIntersectionFactor',
      'causticIntensity',
      'specularIntensity',
      'depthFadeDistance',
      'depthFadeExponent',
      'boatCollisionCenter',
      'islandCollisionCenter',
      'boatCollisionRadius',
      'islandCollisionRadius',
      'boatIntersectionFoamFieldBounds',
      'islandIntersectionFoamFieldBounds',
      'boatIntersectionFoamFieldMaxDistance',
      'islandIntersectionFoamFieldMaxDistance',
      'boatIntersectionFoamFieldValid',
      'islandIntersectionFoamFieldValid',
      'collisionFoamStrength',
      'skyReflectionMix',
      'normalDetailStrength',
      'normalDistanceFalloff',
      'underwaterEnabled',
      'underwaterTransitionDepth',
      'underwaterFogDensity',
      'underwaterHorizonMix',
      'underwaterColorR',
      'underwaterColorG',
      'underwaterColorB',
      'underwaterFactor',
      'profileShallowColor',
      'profileMidColor',
      'profileDeepColor',
      'profileFoamColor',
      'profileScatterColor',
      'profileReflectionColor',
      'profileHorizonGlow',
      'profileFresnelBase',
      'profileFresnelStrength',
      'profileFresnelPower',
      'profileDepthViewScale',
      'profileToneGamma',
      'profileSpecularClamp',
    ],
    attributes: ['position', 'normal', 'uv'],
    samplers: ['boatIntersectionFoamField', 'islandIntersectionFoamField'],
    uniformBuffers: ['Scene', 'Mesh'],
  },

  defaults: {
    time: 0,
    cameraPosition: [0, 50, -100],
    waveAmplitude: 1.8,
    waveFrequency: 1.2,
    windDirection: 45,
    windSpeed: 0.6,
    crestFoamEnabled: 1,
    crestFoamThreshold: 0.45,
    foamIntensity: 0.7,
    foamWidth: 1.0,
    foamNoiseFactor: 0.45,
    foamCellScale: 0.115,
    foamShredSlope: 0.56,
    foamFizzWeight: 0.28,
    intersectionFoamEnabled: 1,
    intersectionFoamIntensity: 1,
    intersectionFoamWidth: 1,
    intersectionFoamFalloff: 1,
    intersectionFoamNoise: 0.45,
    intersectionFoamVerticalRange: 1.8,
    boatIntersectionFactor: 0,
    islandIntersectionFactor: 0,
    causticIntensity: 0.85,
    specularIntensity: 1.0,
    depthFadeDistance: 1.15,
    depthFadeExponent: 1.65,
    boatCollisionCenter: [0, 0.4, -12],
    islandCollisionCenter: [22, 0, 10],
    boatCollisionRadius: 2.2,
    islandCollisionRadius: 4.0,
    boatIntersectionFoamFieldBounds: [-16, -28, 8, 8],
    islandIntersectionFoamFieldBounds: [16, 4, 12, 12],
    boatIntersectionFoamFieldMaxDistance: 6,
    islandIntersectionFoamFieldMaxDistance: 8,
    boatIntersectionFoamFieldValid: 0,
    islandIntersectionFoamFieldValid: 0,
    collisionFoamStrength: 1.0,
    skyReflectionMix: 0.72,
    normalDetailStrength: 0.55,
    normalDistanceFalloff: 0.03,
    underwaterEnabled: 1,
    underwaterTransitionDepth: 8,
    underwaterFogDensity: 0.32,
    underwaterHorizonMix: 0.38,
    underwaterColorR: 0.03,
    underwaterColorG: 0.16,
    underwaterColorB: 0.24,
    underwaterFactor: 0,
    profileShallowColor: [0.055, 0.26, 0.38],
    profileMidColor: [0.012, 0.11, 0.21],
    profileDeepColor: [0.003, 0.02, 0.06],
    profileFoamColor: [0.78, 0.88, 0.95],
    profileScatterColor: [0.0, 0.06, 0.095],
    profileReflectionColor: [0.74, 0.86, 0.98],
    profileHorizonGlow: [0.05, 0.09, 0.13],
    profileFresnelBase: 0.02,
    profileFresnelStrength: 0.74,
    profileFresnelPower: 5.0,
    profileDepthViewScale: 230,
    profileToneGamma: 0.94,
    profileSpecularClamp: 0.22,
  },
  
  setup: (context: ShaderContext) => {
    console.log('🎨 Setting up Gerstner Waves shader');
  },
  
  update: (context: ShaderContext, deltaTime: number) => {
    // Update logic here
  },
  
  cleanup: () => {
    console.log('🧹 Cleaning up Gerstner Waves shader');
  },
};
