import { ShaderContext } from '../ShaderContext';
import { ShaderRegistryEntry } from '../ShaderRegistry';
import { waterVertexShader, profiledOceanFragmentShader } from '../wgsl';

export const glassyWavesDefinition: ShaderRegistryEntry = {
  id: 'glassyWaves',
  displayName: 'Glassy Waves',
  description: 'Low-chop reflective water profile with smooth highlights',
  
  features: {
    supportsFoam: true,
    supportsCaustics: false,
    supportsCollisions: true,
    supportsWake: false,
  },
  
  shader: {
    vertex: waterVertexShader,
    fragment: profiledOceanFragmentShader,
  },
  
  babylon: {
    uniforms: [
      'time',
      'cameraPosition',
      'waveAmplitude',
      'waveFrequency',
      'windDirection',
      'windSpeed',
      'crestFoamEnabled',
      'crestFoamThreshold',
      'foamIntensity',
      'foamWidth',
      'foamNoiseFactor',
      'intersectionFoamEnabled',
      'intersectionFoamIntensity',
      'intersectionFoamWidth',
      'intersectionFoamFalloff',
      'intersectionFoamNoise',
      'intersectionFoamVerticalRange',
      'boatCollisionCenter',
      'islandCollisionCenter',
      'boatCollisionRadius',
      'islandCollisionRadius',
      'boatIntersectionFactor',
      'islandIntersectionFactor',
      'specularIntensity',
      'depthFadeDistance',
      'depthFadeExponent',
      'underwaterEnabled',
      'underwaterTransitionDepth',
      'underwaterFogDensity',
      'underwaterHorizonMix',
      'underwaterColorR',
      'underwaterColorG',
      'underwaterColorB',
      'underwaterFactor',
      'profileShallowColor',
      'profileMidColor',
      'profileDeepColor',
      'profileFoamColor',
      'profileScatterColor',
      'profileReflectionColor',
      'profileHorizonGlow',
      'profileFresnelBase',
      'profileFresnelStrength',
      'profileFresnelPower',
      'profileDepthViewScale',
      'profileToneGamma',
      'profileSpecularClamp',
    ],
    attributes: ['position', 'normal', 'uv'],
    uniformBuffers: ['Scene', 'Mesh'],
  },

  defaults: {
    time: 0,
    cameraPosition: [0, 50, -100],
    waveAmplitude: 1.8,
    waveFrequency: 1.1,
    windDirection: 45,
    windSpeed: 0.4,
    crestFoamEnabled: 1,
    crestFoamThreshold: 0.58,
    foamIntensity: 0.34,
    foamWidth: 0.72,
    foamNoiseFactor: 0.4,
    intersectionFoamEnabled: 1,
    intersectionFoamIntensity: 1,
    intersectionFoamWidth: 1,
    intersectionFoamFalloff: 1,
    intersectionFoamNoise: 0.42,
    intersectionFoamVerticalRange: 1.8,
    boatCollisionCenter: [0, 0.4, -12],
    islandCollisionCenter: [22, 0, 10],
    boatCollisionRadius: 2.2,
    islandCollisionRadius: 4.0,
    boatIntersectionFactor: 0,
    islandIntersectionFactor: 0,
    specularIntensity: 1.2,
    depthFadeDistance: 0.95,
    depthFadeExponent: 1.2,
    underwaterEnabled: 1,
    underwaterTransitionDepth: 8,
    underwaterFogDensity: 0.24,
    underwaterHorizonMix: 0.3,
    underwaterColorR: 0.04,
    underwaterColorG: 0.17,
    underwaterColorB: 0.24,
    underwaterFactor: 0,
    profileShallowColor: [0.18, 0.48, 0.58],
    profileMidColor: [0.07, 0.26, 0.34],
    profileDeepColor: [0.03, 0.1, 0.16],
    profileFoamColor: [0.86, 0.92, 0.96],
    profileScatterColor: [0.02, 0.06, 0.08],
    profileReflectionColor: [0.8, 0.9, 0.98],
    profileHorizonGlow: [0.08, 0.12, 0.15],
    profileFresnelBase: 0.03,
    profileFresnelStrength: 0.78,
    profileFresnelPower: 5.2,
    profileDepthViewScale: 210,
    profileToneGamma: 0.92,
    profileSpecularClamp: 0.26,
  },
  
  setup: (context: ShaderContext) => {
    console.log('🎨 Setting up Glassy Waves shader');
  },
  
  update: (context: ShaderContext, deltaTime: number) => {
    // Update logic here
  },
  
  cleanup: () => {
    console.log('🧹 Cleaning up Glassy Waves shader');
  },
};
