import { ShaderContext } from '../ShaderContext';
import { ShaderRegistryEntry } from '../ShaderRegistry';
import { waterVertexShader, profiledOceanFragmentShader } from '../wgsl';

export const stormyWavesDefinition: ShaderRegistryEntry = {
  id: 'stormyWaves',
  displayName: 'Stormy Waves',
  description: 'Photoreal storm water with heavy trough contrast and crest breakup',
  
  features: {
    supportsFoam: true,
    supportsCaustics: false,
    supportsCollisions: true,
    supportsWake: false,
  },
  
  shader: {
    vertex: waterVertexShader,
    fragment: profiledOceanFragmentShader,
  },
  
  babylon: {
    uniforms: [
      'time',
      'cameraPosition',
      'waveAmplitude',
      'waveFrequency',
      'windDirection',
      'windSpeed',
      'crestFoamEnabled',
      'crestFoamThreshold',
      'foamIntensity',
      'foamWidth',
      'foamNoiseFactor',
      'intersectionFoamEnabled',
      'intersectionFoamIntensity',
      'intersectionFoamWidth',
      'intersectionFoamFalloff',
      'intersectionFoamNoise',
      'intersectionFoamVerticalRange',
      'boatCollisionCenter',
      'islandCollisionCenter',
      'boatCollisionRadius',
      'islandCollisionRadius',
      'boatIntersectionFactor',
      'islandIntersectionFactor',
      'specularIntensity',
      'depthFadeDistance',
      'depthFadeExponent',
      'underwaterEnabled',
      'underwaterTransitionDepth',
      'underwaterFogDensity',
      'underwaterHorizonMix',
      'underwaterColorR',
      'underwaterColorG',
      'underwaterColorB',
      'underwaterFactor',
      'profileShallowColor',
      'profileMidColor',
      'profileDeepColor',
      'profileFoamColor',
      'profileScatterColor',
      'profileReflectionColor',
      'profileHorizonGlow',
      'profileFresnelBase',
      'profileFresnelStrength',
      'profileFresnelPower',
      'profileDepthViewScale',
      'profileToneGamma',
      'profileSpecularClamp',
    ],
    attributes: ['position', 'normal', 'uv'],
    uniformBuffers: ['Scene', 'Mesh'],
  },

  defaults: {
    time: 0,
    cameraPosition: [0, 50, -100],
    waveAmplitude: 1.8,
    waveFrequency: 1.2,
    windDirection: 45,
    windSpeed: 0.75,
    crestFoamEnabled: 1,
    crestFoamThreshold: 0.42,
    foamIntensity: 0.82,
    foamWidth: 1.18,
    foamNoiseFactor: 0.58,
    intersectionFoamEnabled: 1,
    intersectionFoamIntensity: 1,
    intersectionFoamWidth: 1,
    intersectionFoamFalloff: 1,
    intersectionFoamNoise: 0.56,
    intersectionFoamVerticalRange: 1.9,
    boatCollisionCenter: [0, 0.4, -12],
    islandCollisionCenter: [22, 0, 10],
    boatCollisionRadius: 2.2,
    islandCollisionRadius: 4.0,
    boatIntersectionFactor: 0,
    islandIntersectionFactor: 0,
    specularIntensity: 1.1,
    depthFadeDistance: 1.35,
    depthFadeExponent: 2.0,
    underwaterEnabled: 1,
    underwaterTransitionDepth: 8,
    underwaterFogDensity: 0.36,
    underwaterHorizonMix: 0.42,
    underwaterColorR: 0.02,
    underwaterColorG: 0.11,
    underwaterColorB: 0.19,
    underwaterFactor: 0,
    profileShallowColor: [0.045, 0.14, 0.2],
    profileMidColor: [0.02, 0.07, 0.12],
    profileDeepColor: [0.006, 0.018, 0.04],
    profileFoamColor: [0.62, 0.68, 0.74],
    profileScatterColor: [0.0, 0.028, 0.045],
    profileReflectionColor: [0.62, 0.68, 0.75],
    profileHorizonGlow: [0.02, 0.03, 0.05],
    profileFresnelBase: 0.015,
    profileFresnelStrength: 0.76,
    profileFresnelPower: 5.1,
    profileDepthViewScale: 140,
    profileToneGamma: 0.98,
    profileSpecularClamp: 0.16,
  },
  
  setup: (context: ShaderContext) => {
    console.log('🎨 Setting up Stormy Waves shader');
  },
  
  update: (context: ShaderContext, deltaTime: number) => {
    // Update logic here
  },
  
  cleanup: () => {
    console.log('🧹 Cleaning up Stormy Waves shader');
  },
};
