import { ShaderContext } from '../ShaderContext';
import { ShaderRegistryEntry } from '../ShaderRegistry';
import { waterVertexShader, profiledOceanFragmentShader } from '../wgsl';

export const tropicalWavesDefinition: ShaderRegistryEntry = {
  id: 'tropicalWaves',
  displayName: 'Tropical Waves',
  description: 'Photoreal tropical waters with bright shallow color response',
  
  features: {
    supportsFoam: true,
    supportsCaustics: false,
    supportsCollisions: true,
    supportsWake: false,
  },
  
  shader: {
    vertex: waterVertexShader,
    fragment: profiledOceanFragmentShader,
  },
  
  babylon: {
    uniforms: [
      'time',
      'cameraPosition',
      'waveAmplitude',
      'waveFrequency',
      'windDirection',
      'windSpeed',
      'crestFoamEnabled',
      'crestFoamThreshold',
      'foamIntensity',
      'foamWidth',
      'foamNoiseFactor',
      'intersectionFoamEnabled',
      'intersectionFoamIntensity',
      'intersectionFoamWidth',
      'intersectionFoamFalloff',
      'intersectionFoamNoise',
      'intersectionFoamVerticalRange',
      'boatCollisionCenter',
      'islandCollisionCenter',
      'boatCollisionRadius',
      'islandCollisionRadius',
      'boatIntersectionFoamFieldBounds',
      'islandIntersectionFoamFieldBounds',
      'boatIntersectionFoamFieldMaxDistance',
      'islandIntersectionFoamFieldMaxDistance',
      'boatIntersectionFoamFieldValid',
      'islandIntersectionFoamFieldValid',
      'boatIntersectionFactor',
      'islandIntersectionFactor',
      'specularIntensity',
      'depthFadeDistance',
      'depthFadeExponent',
      'underwaterEnabled',
      'underwaterTransitionDepth',
      'underwaterFogDensity',
      'underwaterHorizonMix',
      'underwaterColorR',
      'underwaterColorG',
      'underwaterColorB',
      'underwaterFactor',
      'profileShallowColor',
      'profileMidColor',
      'profileDeepColor',
      'profileFoamColor',
      'profileScatterColor',
      'profileReflectionColor',
      'profileHorizonGlow',
      'profileFresnelBase',
      'profileFresnelStrength',
      'profileFresnelPower',
      'profileDepthViewScale',
      'profileToneGamma',
      'profileSpecularClamp',
    ],
    attributes: ['position', 'normal', 'uv'],
    samplers: ['boatIntersectionFoamField', 'islandIntersectionFoamField'],
    uniformBuffers: ['Scene', 'Mesh'],
  },

  defaults: {
    time: 0,
    cameraPosition: [0, 50, -100],
    waveAmplitude: 1.8,
    waveFrequency: 1.2,
    windDirection: 45,
    windSpeed: 0.6,
    crestFoamEnabled: 1,
    crestFoamThreshold: 0.48,
    foamIntensity: 0.52,
    foamWidth: 0.9,
    foamNoiseFactor: 0.5,
    intersectionFoamEnabled: 1,
    intersectionFoamIntensity: 1,
    intersectionFoamWidth: 1,
    intersectionFoamFalloff: 1,
    intersectionFoamNoise: 0.5,
    intersectionFoamVerticalRange: 1.8,
    boatCollisionCenter: [0, 0.4, -12],
    islandCollisionCenter: [22, 0, 10],
    boatCollisionRadius: 2.2,
    islandCollisionRadius: 4.0,
    boatIntersectionFoamFieldBounds: [-16, -28, 8, 8],
    islandIntersectionFoamFieldBounds: [16, 4, 12, 12],
    boatIntersectionFoamFieldMaxDistance: 6,
    islandIntersectionFoamFieldMaxDistance: 8,
    boatIntersectionFoamFieldValid: 0,
    islandIntersectionFoamFieldValid: 0,
    boatIntersectionFactor: 0,
    islandIntersectionFactor: 0,
    specularIntensity: 0.95,
    depthFadeDistance: 1.0,
    depthFadeExponent: 1.35,
    underwaterEnabled: 1,
    underwaterTransitionDepth: 8,
    underwaterFogDensity: 0.28,
    underwaterHorizonMix: 0.34,
    underwaterColorR: 0.05,
    underwaterColorG: 0.22,
    underwaterColorB: 0.25,
    underwaterFactor: 0,
    profileShallowColor: [0.08, 0.5, 0.48],
    profileMidColor: [0.02, 0.28, 0.34],
    profileDeepColor: [0.01, 0.09, 0.17],
    profileFoamColor: [0.76, 0.89, 0.92],
    profileScatterColor: [0.0, 0.06, 0.08],
    profileReflectionColor: [0.72, 0.84, 0.95],
    profileHorizonGlow: [0.06, 0.1, 0.12],
    profileFresnelBase: 0.03,
    profileFresnelStrength: 0.7,
    profileFresnelPower: 4.6,
    profileDepthViewScale: 170,
    profileToneGamma: 0.94,
    profileSpecularClamp: 0.22,
  },
  
  setup: (context: ShaderContext) => {
    console.log('🎨 Setting up Tropical Waves shader');
  },
  
  update: (context: ShaderContext, deltaTime: number) => {
    // Update logic here
  },
  
  cleanup: () => {
    console.log('🧹 Cleaning up Tropical Waves shader');
  },
};
